### ISSUE TITLE
Token issuance fails

### ISSUE THREAD

**Issue by maudnals** [JackJey/trust-token-issuer-demo#5]
Token issuance fails for me. Not sure whether this is expected?

Chrome 87.0.4280.8 (macOS). Happens in both **regular Chrome** (with company extensions on) and **Incognito**.

To reproduce:
* Open https://trust-token-redeemer-demo.glitch.me/ and follow the steps
* Click the Trust Token issuer link
![image](https://user-images.githubusercontent.com/9762897/101611965-6c8a0280-3a0a-11eb-92ac-5f0ea25e6aa1.png)
* "Issuing..." is displayed and doesn't update
![image](https://user-images.githubusercontent.com/9762897/101611774-36e51980-3a0a-11eb-8226-4d96d7ddd7a4.png) 
 * Error shows when opening the DevTools console: `issuer.js:44 Uncaught (in promise) DOMException: Precondition failed during Trust Tokens operation`
* What I would expect to happen:
A token to be issued.

**Comment by maudnals** [comment]
More specifically:

![image](https://user-images.githubusercontent.com/9762897/101651383-4b8ed500-3a3d-11eb-90de-e93a6d53298c.png)

**Comment by JackJey** [comment]
This demo currently supports trust token v1 only.
For make sure chrome uses v1, please disable flags below.

- `chrome://flags/#enable-experimental-web-platform-features`
- `chrome://flags/#trust-tokens`

**Comment by JackJey** [comment]
according to talk with @maudnals , I think it already solved.
feel free to re-open here if something still wrong.

**Comment by yhgit52** [comment]
Hi @JackJey I'm getting the same issue when building and running the demo myself. I've tested this repo and https://github.com/JackJey/trust-token-demo/ but both had the same issue as below. Any idea on what could be wrong? Thanks!

<img width="688" alt="Screen Shot 2022-08-22 at 3 56 25 PM" src="https://user-images.githubusercontent.com/4314379/186017464-427b57cc-15ec-40f4-ac96-f7509e8513f5.png">

**Comment by JackJey** [comment]
@yhgit52 This demo is not intended to run locally, since TT API is so sensitive about domain it's running.

**Comment by yhgit52** [comment]
Hi @JackJey thanks for your reply. Is it related to original trial or so? i.e. Do we need to register our domain to be in the allowlist or so? Because we were able to run TT V2 locally by following this repo 8 months ago.
