### ISSUE TITLE
Running a similar demo on localhost

### ISSUE THREAD

**Issue by ip2724** [JackJey/trust-token-issuer-demo#6]
Hello, First of all the repo is great resource. 
I was trying to run a similar demo on localhost, after registering localhost for  origin trial. I am trying to issue tokens on localhost, though getting as error as  follows.

![image](https://user-images.githubusercontent.com/84411889/118717987-99bdb680-b7db-11eb-8ff5-6fc16b5326f9.png)

Any pointers on debugging this further is appreciated. In what situations do I expect the preconditions to fail? 

I am starting the chrome as follows

` /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --enable-features=TrustTokens --additional-trust-token-key-commitments='{"http://localhost:5000": "<key>"}'`

Also wanted to know how have you gone about generating <key> here?

**Comment by JackJey** [comment]
@ip2724 Thanks for report and sorry for late reply.

The trust token API is very sensitive for domain. This demo depends on 3 domains below.
- trust-token-demo.glitch.me
- trust-token-issuer-demo.glitch.me
- trust-token-redeemer-demo.glitch.me

And this demo doesn't works locally.

I'm planning adding standalone demo which works locally, so please check it.

FYI: this repo was merged into https://github.com/JackJey/trust-token-demo

Thansk
